// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.API.Data;

#nullable disable

namespace Product.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Product.API.Data.EmailJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailJobs");
                });

            modelBuilder.Entity("Product.API.Data.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrderProduct");

                    b.HasData(
                        new
                        {
                            Id = new Guid("018fc847-db2d-489e-952c-519f5a95b7d3"),
                            Category = "[\"Smart Phone\"]",
                            Description = "This phone is the company's biggest change to it's first line products",
                            ImageFile = "product-1.png",
                            Name = "IPhone XR",
                            Price = 1020.00m
                        },
                        new
                        {
                            Id = new Guid("018fc847-db4d-489e-952c-519f5a95b7d4"),
                            Category = "[\"Smart Phone\"]",
                            Description = "This phone is the company's biggest change to it's first line products",
                            ImageFile = "product-2.png",
                            Name = "Samsung Note 10",
                            Price = 950.00m
                        },
                        new
                        {
                            Id = new Guid("018fc847-db6d-489e-952c-519f5a95b7d5"),
                            Category = "[\"Smart Phone\"]",
                            Description = "This phone is the company's biggest change to it's first line products",
                            ImageFile = "product-3.png",
                            Name = "Tecno Pop 5",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = new Guid("018fc847-db2d-489e-952d-519f5a95b7d6"),
                            Category = "[\"Smart Phone\"]",
                            Description = "This phone is the company's biggest change to it's first line products",
                            ImageFile = "product-4.png",
                            Name = "Infinix Zero 3",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = new Guid("018fc847-db2d-489e-992c-519f5a95b7d7"),
                            Category = "[\"Smart Phone\"]",
                            Description = "This phone is the company's biggest change to it's first line products",
                            ImageFile = "product-5.png",
                            Name = "Huwai Plus",
                            Price = 750.00m
                        },
                        new
                        {
                            Id = new Guid("018fc847-db2d-489e-952c-519f8a95b7d8"),
                            Category = "[\"Home Kitchen\"]",
                            Description = "This phone is the company's biggest change to it's first line products",
                            ImageFile = "product-6.png",
                            Name = "LG G7 ThinQ",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = new Guid("018fc847-db2d-189e-952c-519f5a95b7d9"),
                            Category = "[\"Camera\"]",
                            Description = "This phone is the company's biggest change to it's first line products",
                            ImageFile = "product-7.png",
                            Name = "Panasonic Lumix",
                            Price = 450.00m
                        });
                });

            modelBuilder.Entity("Product.API.Data.ReportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Generated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReportJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
